### ISSUE TITLE
Kommentarer på DiffEq-simuleringen

### ISSUE THREAD

**Issue by baggepinnen** [wahlquisty/pksim#5]
Att kalla på 
```julia
prob = ODEProblem(pk3!, x0, tspan, p)
```
kostar en hel del, men man kan återanvända samma `prob` flera gånger genom att kalla på `remake` för att byta, e.g., initialtillstånd
```julia
new_prob = remake(prob, x0=new_x0, p = new_p, ...)
```

---

För riktigt små problem som dessa är det oftast snabbare att använda StaticArrays för att simulaera än att använda in-place interfacet enligt
```julia
dx[2] = k21 * x[1] - k21 * x[2]
```

jag provar att göra denna ändringen.

Edit: Det verkar inte ha hjälpt så mkt.

---

Datan hanteras som Float32, men lösaren jobbar i Float64, är detta meningen?

**Comment by wahlquisty** [comment]
Jag tänker att det inte gör något att koden inte är så optimerad, eftersom jag har "bara" implementerat enligt exemplena i DifferentialEquations-dokumentationen.
